# Generated by Django 4.2.6 on 2023-10-24 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('course', 'name'), 'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
    ]
